# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de2a3d433e61c3f7a57bb244bc5e17bed5a1c172dd3269840f16b53eef2b4ccac78da39b0ae7138362d6f3cf2d50fa6efcc72162bef2aba3fc85d37b99e519c

test:
  secret_key_base: 4286414b07b1dbcce012d5983f77c4696f1f1a58ae6c86ebc13b2a99de88ee5eff0b8b877c51074cb9bf1af256457b712f6f999bc3913d017636f00533c8dc22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
